### ISSUE TITLE
In version >= 3.1, JSON Configuration fails and falls back to default

### ISSUE THREAD

**Issue by ryantrevisol** [jenkinsci/selenium-plugin#104]
# Issue
After upgrading to 3.1, all my nodes have 5 Firefox, 5 Chrome, and 1 IE. I am using JSON configuration. 

# Steps to Reproduce 

- Install the plugin at version 3.1 
- [Grab the default node config JSON file from SeleniumHQ](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/common/defaults/DefaultNodeWebDriver.json)
- Make minor changes (max instances of browsers, for example)
- Use the JSON file to register to your Jenkins-hosted hub
`java -jar selenium-server-standalone-3.3.1.jar -role node -nodeConfig /tmp/nnn.json`
- Note the config of the registered node: 
*Expected:* Specified browser instances are available
*Actual:* The default configuration of 5 Firefox, 5 Chrome, and 1 IE is applied
*Logged Warning:* 
```
10:34:33.205 WARN - error getting the parameters from the hub. The node may end up with wrong timeouts.Error with the JSON of the config : String hudson.plugins.selenium.JenkinsCapabilityMatcher could not be coerced to class: java.lang.Class
```

I have written a unit test that fails for this issue, and I'm investigating the solution.

**Comment by ryantrevisol** [comment]
Looks like it's a known issue on the Selenium side:
https://github.com/seleniumhq/selenium/issues/3268

**Comment by Mobrockers** [comment]
Ask the selenium developers? I don't know what you expect us to do here.

**Comment by demonkoryu** [comment]
They say "In the interim, if it is important to you that the nodes acquire their timeout value from the hub, please take the work-around and ensure the nodes have the class in their CLASSPATH." and maybe you could give me some pointer as to which jars have to be added for the selenium grid plugin to work?
