### ISSUE TITLE
using "xvfb-run" to not start always a X server

### ISSUE THREAD

**Issue by guilhem** [jenkinsci/selenium-plugin#11]
in my case, the command : 

    /usr/lib/jvm/jdk1.6.0_31/jre/bin/java -cp /home/jenkins/slave.jar hudson.remoting.Launcher -cp /home/jenkins/selenium-server-standalone-2.21.0.jar -connectTo localhost:54466

is launch by this plugin.

An good option will be to run the command with "xvfb-run" :

    # xvfb-run /usr/lib/jvm/jdk1.6.0_31/jre/bin/java -cp /home/jenkins/slave.jar hudson.remoting.Launcher -cp /home/jenkins/selenium-server-standalone-2.21.0.jar -connectTo localhost:54466

it's the only things to do, no need to "DISPLAY" env, no need to have a process X.

**Comment by Mobrockers** [comment]
Since I agree with @darkrift and there has been no comment on this by requester since 2012 I'm closing this issue.
