### ISSUE TITLE
how do we specify the chromedriver / geckodriver executables in jenkins selenium plugin

### ISSUE THREAD

**Issue by mrunalgosar** [jenkinsci/selenium-plugin#117]
1) How do we specify the chromedriver / geckodriver executables in jenkins selenium plugin configuration?
2) When in master / slave configuration where should we keep this executables and how would it get copied to slave host?

**Comment by flipy** [comment]
There is plugin to download and deploy automatically the chromedriver in Jenkins:
 [https://plugins.jenkins.io/chromedriver](url)

As for Firefox, it needs to use the GeckoDriver, but the only option available is to set up the Firefox binary path.
The output error after that is: `org.openqa.selenium.SessionNotCreatedException: Unable to create new service: GeckoDriverService`

**Comment by jameswtelfer** [comment]
So far as I know, the Geckodriver is not configurable (possibly not supported at all) by this plugin, see #83 for the general case.

**Comment by Mobrockers** [comment]
@flipy Firefox binary path is the path to the Firefox **browser** binary, not the Firefox **driver** binary. Currently only the old Java firefox driver is supported. Feel free to add support for geckodriver.

**Comment by Mobrockers** [comment]
I am closing this issue as it is already covered in #83
