### ISSUE TITLE
Update  the plugin to 3.14.0 and the htmlunit to 2.32.1

### ISSUE THREAD

**Issue by alinpa** [jenkinsci/selenium-plugin#132]
Hello, 

Can someone help me to update the selenium plugin to use the latest version of selenium version and the latest version of htmlunit?
Selenium to 3.14.0 
Htmlunit to 2.32.1

**Comment by Mobrockers** [comment]
See https://github.com/jenkinsci/selenium-plugin/blob/master/UPDATE-SELENIUM-README.md and https://github.com/jenkinsci/selenium-plugin/blob/master/UPDATE-HTMLUNITDRIVER-README.md
