### ISSUE TITLE
Remove RC support.

### ISSUE THREAD

**Issue by dmitryyu** [jenkinsci/selenium-plugin#136]
Selenium 3.xx version doesn't support Selenium RC. 
I guess it's time to remove RC configuration from the plugin.

**Comment by Mobrockers** [comment]
Selenium 3.xx does support Selenium RC. They have dropped in a webdriver backed replacement behind all the api's which means that nearly all RC tests should remain functional. Until Selenium fully removes this functionality I see no reason to touch this part of the code (unless it's broken of course). See https://seleniumhq.wordpress.com/2016/10/04/selenium-3-is-coming/

**Comment by dmitryyu** [comment]
Agree, didn’t know that RC is still there.
