### ISSUE TITLE
Wrong IP address

### ISSUE THREAD

**Issue by guilhem** [jenkinsci/selenium-plugin#14]
I just update to the last 2.1 version (which is fabulous).

But I have quite a big problem :
I ran jenkins slave on a Ubuntu server, everything work great for jenkins (build etc) but selenium grid try to use a bad IP (ip from a non-used bridge which is unreachable from the jenkins server).

Selenium plugin must use the "good" address find in the node configuration.

**Comment by thaitzer** [comment]
Hi!

I know this is an old thread. But after the update from 2.53 to 3.x this is a regression for me. 

My selenium node is running on a rented virtual machine that does not know its public ip (although it has a public IP where all traffic is forwarded to it). With the previous plugin version, the host parameter from the json configuration was correctly used to connect to the configured host. With the currently installed version (3.1.0) this no longer works as the host parameter from the json config is ignored.

Any ideas what I should do?

**Comment by Mobrockers** [comment]
Nothing about host configuration was changed here as far as I know, I suggest you try the selenium team?

**Comment by thaitzer** [comment]
Thank you for the fast response!

I will do that.
