### ISSUE TITLE
SEVERE: Port 4444 is busy, please choose a free port for the hub and specify it using -port option

### ISSUE THREAD

**Issue by lucasheringer** [jenkinsci/selenium-plugin#142]
After install this plugin and trying to use it I keep getting this error:

> SEVERE: Port 4444 is busy, please choose a free port for the hub and specify it using -port option

Port is open and not used by anything, If I try to connect to the grid I get connection refused.
Jenkins is running on a docker container and below is my docker start command:

> docker run --rm -p 8080:8080 -p 50000:50000 -p 4444:4444 -v /Users/lheringer/jenkins:/var/jenkins_home/ jenkins/jenkins:lts

Selenium Plugin console output:

> Starting Selenium Grid
[jenkins_home] $ /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -cp /var/jenkins_home/war/WEB-INF/lib/remoting-3.27.jar hudson.remoting.Launcher -cp /var/jenkins_home/plugins/selenium/WEB-INF/lib/selenium-server-standalone-3.12.0.jar:/var/jenkins_home/plugins/selenium/WEB-INF/lib/selenium-server-standalone-3.12.0.jar -connectTo localhost:38761
Starting Selenium Grid
channel started
Apr 29, 2019 2:36:17 PM hudson.plugins.selenium.HubLauncher call
OFF: Grid hub starting with log level ALL
Apr 29, 2019 2:36:17 PM hudson.plugins.selenium.HubLauncher call
OFF: Grid Hub preparing to start on port 4444
2019-04-29 14:36:19.089:INFO::pool-1-thread-2 for channel id=0: Logging initialized @25689ms to org.seleniumhq.jetty9.util.log.StdErrLog
2019-04-29 14:36:19.531:INFO:osjs.Server:pool-1-thread-2 for channel id=0: jetty-9.4.7.v20170914, build timestamp: 2017-11-21T21:27:37Z, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
2019-04-29 14:36:19.881:INFO:osjs.session:pool-1-thread-2 for channel id=0: DefaultSessionIdManager workerName=node0
2019-04-29 14:36:19.882:INFO:osjs.session:pool-1-thread-2 for channel id=0: No SessionScavenger set, using defaults
2019-04-29 14:36:19.886:INFO:osjs.session:pool-1-thread-2 for channel id=0: Scavenging every 600000ms
2019-04-29 14:36:19.953:INFO:osjsh.ContextHandler:pool-1-thread-2 for channel id=0: Started o.s.j.s.ServletContextHandler@4ea4dfe3{/,null,AVAILABLE}
2019-04-29 14:36:20.033:INFO:osjs.AbstractConnector:pool-1-thread-2 for channel id=0: Stopped ServerConnector@1c68bfde{HTTP/1.1,[http/1.1]}{jenkins-master.gr.brighttalk.com:4444}
2019-04-29 14:36:20.034:INFO:osjs.session:pool-1-thread-2 for channel id=0: Stopped scavenging
Apr 29, 2019 2:36:19 PM org.openqa.grid.internal.DefaultGridRegistry assignRequestToProxy
INFO: Shutting down registry.
2019-04-29 14:36:20.040:INFO:osjsh.ContextHandler:pool-1-thread-2 for channel id=0: Stopped o.s.j.s.ServletContextHandler@4ea4dfe3{/,null,UNAVAILABLE}
Apr 29, 2019 2:36:20 PM org.openqa.grid.web.Hub start
SEVERE: Port 4444 is busy, please choose a free port for the hub and specify it using -port option
Apr 29, 2019 2:36:20 PM hudson.plugins.selenium.HubLauncher call
OFF: Grid Hub started on port 4444 with args: -maxSession 5 -timeout 300 -browserTimeout 0 -host jenkins-master.gr.brighttalk.com
Apr 29, 2019 2:37:13 PM org.jenkinsci.remoting.util.AnonymousClassWarnings warn
WARNING: Attempt to (de-)serialize anonymous class hudson.plugins.selenium.PluginImpl$1; see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
￼

Just one more thing, if I bash into the Jenkins master container, remove this plugin and manually start the Selenium hub it works fine using the same port and same version.

**Comment by rogerfc** [comment]
The same issue happens to me, and changing the port does not help.

**Comment by darkrift** [comment]
See #128

**Comment by lucasheringer** [comment]
Thanks @darkrift for pointing that issue.

Just if anyone need, the workaround is to go to Manage Jenkins -> Configure System -> Click Advanced at Selenium config and select "Use a fixed hostname" setting to "0.0.0.0"

That fixed for me.

**Comment by rogerfc** [comment]
After using the workaround to start the server, I realized there was a problem with port 4444, which was blocked. After opening the port properly, I was able to set the hostname to the proper value, not 0.0.0.0. So, after all, not only the 'port busy' is quite misleading, but the server does not start unless the port is opened. Weird and confusing.

**Comment by darkrift** [comment]
@rogerfc Have u tried reverting the advanced options after “opening the port” to confirm this was a problems to start with ?

The default mechanism when not using the advanced option is to try to use the resolved ip from the jenkins configured url

One of the problems that can occur is if your configured jenkins url resolve to an ip which is not associated to this jenkins server but a load balancer or an external endpoint. The server will not able to bind to this ip and will fail.

The only reasons for the bind to fail is explained in the other issue : either the port is busy (or not available for normal user if <= 1023 which is reserved to root) or the ip it tries to bind on is not configured for the jenkins server.

**Comment by rogerfc** [comment]
@darkrift that was exactly the case, our jenkins instance was behind a load balancer. Using the private ip for the instance in the advanced settings worked fine after opening the port.

**Comment by darkrift** [comment]
@rogerfc what I’m saying is that for the plugin to start and listen on the port, u shouldn’t have needed to open the port in the firewall rules. Binding a port is unrelated to other connecting to it.
