### ISSUE TITLE
Selenium server terminates on RDP logoff

### ISSUE THREAD

**Issue by palek** [jenkinsci/selenium-plugin#15]
Our jenkins master running on XP. Selenium hub terminates when I logoff RDP session. Selenium port is inaccessible, and nodes disappear from status page of the grid.

This problem has been discussed in this topic: http://jenkins.361315.n4.nabble.com/Logging-out-of-an-RDP-session-causes-builds-to-fail-td383975.html

**Comment by Mobrockers** [comment]
Since this is, according to kohsuke, a bug in Java, and no pull request has been filed for this issue, nor has anyone else commented, I am closing this issue without manually pulling downstream changes.
