### ISSUE TITLE
How does one upgrade the Selenium version? 

### ISSUE THREAD

**Issue by timc3** [jenkinsci/selenium-plugin#23]
Currently at the time of writing 2.28 is the latest which I would like to run (I think it might solve a problem I have with running against Firefox 18).

How do we upgrade the jar file as needed?

**Comment by CRuppert** [comment]
@darkrift are we going to see a release any time soon? I see you have updated the selenium version in the repo

**Comment by Mobrockers** [comment]
@CRuppert I will try to release the new version tonight.
