### ISSUE TITLE
Can't set the timeout field

### ISSUE THREAD

**Issue by maxoumime** [jenkinsci/selenium-plugin#36]
Hi everybody,

I'm trying to configure the Selenium plugin in the configuration panel, and when I'm trying to attribute a value to the timeout field, after I save the configuration, the field is blank...

(sorry for my english)

**Comment by drodil** [comment]
I am having the same problem. Tried also to change the timeout to /var/lib/jenkins/selenium.xml but it seems it's not working either. This is really frustrating issue as some of the test cases take longer than the default 30 seconds to run. 

Any workarounds for this or just wait for the new version of the plugin?

**Comment by Ben-Mark** [comment]
Any updates on the issue? I'm experiencing it as well

**Comment by Mobrockers** [comment]
Was fixed for 2.53.0
