### ISSUE TITLE
"Custom RC node configuration" produces config lacking JVM options and starred browser names

### ISSUE THREAD

**Issue by romanrev** [jenkinsci/selenium-plugin#37]
Also logged [on Jenkins JRIA](https://issues.jenkins-ci.org/browse/JENKINS-21473) but it seems to my eye a bit stale, so might be picked up here earlier

"Custom RC node configuration" in Selenium plugin produces a config which lacks the essential JVM option - Chrome driver location, though it is supplied in the "Chrome binary path" field. Same config produced with "Custom web driver configuration" sets the JVM 'webdriver.chrome.driver' option, as could be seen from the attached screenshots. 

![custom rc node configuration](https://f.cloud.github.com/assets/2794589/1980982/38387d54-83cd-11e3-8d41-46c8d8a5845b.png)

![custom web node configuration](https://f.cloud.github.com/assets/2794589/1980985/4b7288b0-83cd-11e3-94b5-4f8783b38db5.png)

Also `browserName` settings have different names to those obtained through "Custom web driver configuration" (please refer to the screenshots again):

"Custom web driver config": browserNames - `firefox`, `chrome`
"Custom RC node config": browserNames - `*firefox`, `*googlechrome`

At the moment it prevents me from using the "Custom RC node config" which I need to use the `-log` and `-browserLog` options.

I think it would be also beneficial to merge those two different ways to configure Selenium server into one, by simply adding a 'JVM options' field to one of them.

**Comment by Mobrockers** [comment]
Closing because it has been fixed some time ago.
