### ISSUE TITLE
Unable to set unique hostname in config

### ISSUE THREAD

**Issue by cshope** [jenkinsci/selenium-plugin#39]
When attempting to set a unique hostname in the Selenium plugin config, the field seemingly does not save (page refreshes and the field is blank). Upon further inspection, the unique hostname is in the header request, however the post throws a 302 redirect response. 

Newest version of the Selenium plugin
Red Hat Enterprise Linux Server release 5.10 (Tikanga)
Java 1.6.0_35
Jenkins 1.548

**Comment by t5unamie** [comment]
can someone outline where the selenium.xml file is. a find in the jenkins home folder shows nothing.

**Comment by DarkGigaByte** [comment]
Hi @t5unamie 

The selenium.xml is located in the home directory of your jenkins installation, in most cases "/var/lib/jenkins".
You can simply create it if it isn't there, heres a basic template for you: https://gist.github.com/DarkGigaByte/46692091a1c6cef8b57a

**Comment by sne11ius** [comment]
Is this fixed by 1e3486b0ebb77f47ee940698700482311f8bdce9 ?

**Comment by Mobrockers** [comment]
@sne11ius Yes this is fixed by that commit. I will release an update with the changes soon.
