### ISSUE TITLE
Can't connect the node to the hub (couldn't register this node)

### ISSUE THREAD

**Issue by JulienBreton** [jenkinsci/selenium-plugin#42]
Hello,

I use the Selenium plugin of Jenkins.
On my Jenkins master (Ubuntu) I created a slave. 
This slave is launched by JNLP on a VM (VirtualBox Ubuntu).
The communication between the master and the slave is OK.
I created a Selenium node configuration.
When I go to the Selenium Grid on Jenkins I see : "No RCs have checked in yet. Have you started some slaves?"
When I watch the logs of the slave I see : "09:37:22.618 INFO - couldn't register this node : Hub is down or not responding: Connect to ... failed: Connection refused"

The firewall is off.

I decided to test Selenium Grid without Jenkins. I launch manually the Selenium hub on my computer and the Selenium node on my VM and it's work perfectly.
So I supposse it's not a network problem but a Jenkins configuration problem.

I tried with a Windows 8 and a VM Ubuntu and I have the same error "couldn't register this node...".

When I do this command : nmap -p 4444 -sT IPmaster I get :
Port 4444/tcp State Closed Service krb524 
Closed = nothing uses this port.

If I launch the same command when I launch the Selenium hub manually (without Jenkins), the port is openned.

What kind of Jenkins slave I should creat?
Do you think there is an issue wirth the Selenium plugin?

Thanks for your help.

Julien

**Comment by marycats** [comment]
Have the same issue with Jenkins Selenium plugin: unable to register node from external machine. I also unable to reach grid console from external machine when hub is launched with jenkins (I'm able to reach it when I start hub manually)

**Comment by kenhosr** [comment]
same issue, investigating.

**Comment by Mobrockers** [comment]
Can anyone confirm this is till happening to them on version 2.53.0?

**Comment by Mobrockers** [comment]
I am going to assume this bug is no longer relevant until I hear otherwise. Feel free to comment if you still experience this issue.

**Comment by virendrachaudhary06** [comment]
I am still facing this issue even with version 2.53.0 if node is on external machine. I am using JSON configuration to configure and following is the JSON that I am putting in node configuration file.

{
"class": "org.openqa.grid.common.RegistrationRequest",
"capabilities": [
 {
 "seleniumProtocol": "WebDriver",
 "browserName": "firefox",
 "version": "47",
 "maxInstances": 1,
 "platform" : "WINDOWS"
 }
],
"configuration": {
 "port": 8989,
 "register": true,
 "host": "10.4.3.221",
 "proxy": "org.openqa.grid.selenium.proxy.
 DefaultRemoteProxy",
 "maxSession": 1,
 "hubHost": "10.4.3.221",
 "role": "webdriver",
 "registerCycle": 5000,
 "hub": "http://10.4.3.221:4444/grid/register",
 "hubPort": 4444,
 "remoteHost": "http://10.4.3.221:8989"
}
}

Following is logs of that node

JNLP agent connected from /10.4.3.145
<===[JENKINS REMOTING CAPACITY]===>Slave.jar version: 2.57
This is a Windows slave
Starting Selenium nodes on RecallNode
Creating selenium node VM
$ "C:\Program Files\Java\jre7\bin\java" -Dwebdriver.ie.driver=C:\Jenkins\IEDriverServer.exe -cp C:\Users\abhishekja\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\55\7d62e077-2c89163c hudson.remoting.Launcher -cp C:\Jenkins\selenium-server-standalone-2.53.0.jar;C:\Jenkins\htmlunit-driver-standalone-2.20.jar -connectTo localhost:52126
Starting the selenium node process. Args: [-role, node, -hub, http://localhost:4444/wd/hub, -port, 4445, -maxSession, 1, -browser, seleniumProtocol=WebDriver,browserName=internet explorer,maxInstances=1, -browser, seleniumProtocol=WebDriver,browserName=firefox,maxInstances=1, -browser, seleniumProtocol=WebDriver,browserName=chrome,maxInstances=1, -host, 9bbkyx1.pyramidconsultinginc.com]
channel started
Creating selenium node VM
$ "C:\Program Files\Java\jre7\bin\java" -cp C:\Users\abhishekja\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\55\7d62e077-2c89163c hudson.remoting.Launcher -cp C:\Jenkins\selenium-server-standalone-2.53.0.jar;C:\Jenkins\htmlunit-driver-standalone-2.20.jar -connectTo localhost:52128
Starting the selenium node process. Args: [-role, node, -hub, http://localhost:4444/wd/hub, -hub, http://10.4.3.221:4444/wd/hub, -host, 10.4.3.221, -nodeConfig, C:\Jenkins\selenium-temp-config-1466599256795.json, -host, 9bbkyx1.pyramidconsultinginc.com]
channel started
Slave successfully connected and online
Jun 22, 2016 6:10:59 PM org.openqa.grid.common.RegistrationRequest addCapabilityFromString
INFO: Adding seleniumProtocol=WebDriver,browserName=internet explorer,maxInstances=1
Jun 22, 2016 6:10:59 PM org.openqa.grid.common.RegistrationRequest addCapabilityFromString
INFO: Adding seleniumProtocol=WebDriver,browserName=firefox,maxInstances=1
Jun 22, 2016 6:10:59 PM org.openqa.grid.common.RegistrationRequest addCapabilityFromString
INFO: Adding seleniumProtocol=WebDriver,browserName=chrome,maxInstances=1
Jun 22, 2016 6:11:02 PM org.openqa.grid.internal.utils.SelfRegisteringRemote <init>
WARNING: error getting the parameters from the hub. The node may end up with wrong timeouts.Connect to localhost:4444 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
Jun 22, 2016 6:11:02 PM org.openqa.grid.internal.utils.SelfRegisteringRemote <init>
WARNING: error getting the parameters from the hub. The node may end up with wrong timeouts.Connect to localhost:4444 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
18:11:02.735 INFO - Java: Oracle Corporation 24.60-b09
18:11:02.736 INFO - OS: Windows 7 6.1 amd64
18:11:02.736 INFO - Java: Oracle Corporation 24.60-b09
18:11:02.736 INFO - OS: Windows 7 6.1 amd64
18:11:02.756 INFO - v2.53.0, with Core v2.53.0. Built from revision 35ae25b
18:11:02.757 INFO - v2.53.0, with Core v2.53.0. Built from revision 35ae25b
18:11:03.031 INFO - Driver class not found: com.opera.core.systems.OperaDriver
18:11:03.032 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
18:11:03.031 INFO - Driver class not found: com.opera.core.systems.OperaDriver
18:11:03.033 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
18:11:03.149 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
registration capabilities Capabilities [{platform=MAC, browserName=safari, version=}] does not match the current platform VISTA
18:11:03.149 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
registration capabilities Capabilities [{platform=MAC, browserName=safari, version=}] does not match the current platform VISTA
18:11:03.299 INFO - Version Jetty/5.1.x
18:11:03.300 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
18:11:03.301 INFO - Started HttpContext[/selenium-server,/selenium-server]
18:11:03.301 INFO - Started HttpContext[/,/]
18:11:03.303 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@3adec164
18:11:03.303 INFO - Started HttpContext[/wd,/wd]
18:11:03.314 INFO - Version Jetty/5.1.x
18:11:03.315 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
18:11:03.317 INFO - Started HttpContext[/selenium-server,/selenium-server]
18:11:03.317 INFO - Started HttpContext[/,/]
18:11:03.319 INFO - Started SocketListener on 0.0.0.0:4445
18:11:03.319 INFO - Started org.openqa.jetty.jetty.Server@2462ea85
18:11:03.321 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@1cda48dc
18:11:03.321 INFO - Started HttpContext[/wd,/wd]
18:11:03.325 INFO - Started SocketListener on 0.0.0.0:8989
18:11:03.341 INFO - Started org.openqa.jetty.jetty.Server@1639a35
18:11:03.402 INFO - Starting auto registration thread. Will try to register every 5000 ms.
18:11:03.402 INFO - Starting auto registration thread. Will try to register every 5000 ms.
18:11:03.402 INFO - Registering the node to the hub: http://**localhost**:4444/grid/register
18:11:03.402 INFO - Registering the node to the hub: http://localhost:4444/grid/register
18:11:05.429 INFO - Couldn't register this node: Error sending the registration request: Connect to **localhost:**4444 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect

I am not sure why it is taking localhost not the exact IP of the hub machine.

**Comment by Mobrockers** [comment]
It's most likely using localhost because you have not set a jenkins url in jenkins config (which then defaults to localhost), and you are using the jenkins url as the selenium hub url (which is then thus localhost). You need to set a custom selenium hostname in the jenkins main configuration page, under selenium hostname resolver.

**Comment by virendrachaudhary06** [comment]
I made this change. Now I am getting below error - 
19:31:02.922 INFO - Registering the node to the hub: http://10.4.3.221:4444/grid/register
19:31:02.930 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error

**Comment by Mobrockers** [comment]
Does the hub log say anything about the internal server error?

**Comment by virendrachaudhary06** [comment]
Thank You. It is working now if I am using Custom web driver node configuration option. I am still not sure what is the correct JSON configuration to configure a node.

**Comment by Mobrockers** [comment]
Here: https://stackoverflow.com/questions/7405912/where-can-i-find-a-schema-or-documentation-for-the-se-2-grid-hub-configuration-j

You can find an example for a correct node json file, which yours clearly is not.
