### ISSUE TITLE
IEDriverServer download is slow and is forced each restart

### ISSUE THREAD

**Issue by GregDomjan** [jenkinsci/selenium-plugin#45]
Finding that on restart with our slow network a node can take 10-15 minutes to restart mainly due to waiting for IEDriverServer to re install.

The 'IfNecessary' part of the `uploadIEDriverIfNecessary` is currently deciding it is always necessary.

`final InputStream is = new RemoteInputStream(url.openStream());` 
`RemoteInputStream(Stream)` is deprecated, on resolution is to add the Flag param, suggest to improve performance of sending largish file using GREEDY option.
 `final InputStream is = new RemoteInputStream(url.openStream(),RemoteInputStream.Flag.GREEDY);`

- I'd fork and send a pull, but I can't build and test yet

**Comment by Mobrockers** [comment]
Implemented in #70 but will see if it's possible to detach iedriver download from this project completely.
