### ISSUE TITLE
Editing plugin configuration in Jenkins' "Configure System" page does nothing

### ISSUE THREAD

**Issue by talcloudshare** [jenkinsci/selenium-plugin#57]
I am trying to change the plugin setting in Jenkins' "Configure System" page, but after clicking Save/Apply nothing is being saved

![image](https://cloud.githubusercontent.com/assets/11614000/14532617/59662bfc-026a-11e6-8db1-a87c2f21a479.png)

Please advise

Thanks

**Comment by Mobrockers** [comment]
Please note, the selenium hub configuration page is missing in the next release, due to changes started but not finished (I'm guessing) by @darkrift. I will see if I can restore this after the next release.

**Comment by Mobrockers** [comment]
Was fixed for version 2.53.0
