### ISSUE TITLE
Add ability to choose which verison of IEDriverServer is downloaded to node

### ISSUE THREAD

**Issue by zdmeyers** [jenkinsci/selenium-plugin#72]
Currently, if the plugin determines that a Windows node is 64-bit, it will download the 64-bit IEDriverServer.exe to the node. Same goes for 32-bit. However, it has been proven that using the 64-bit IEDriverServer on a 32-bit IE will cause extreme slowness in executing certain actions (namely, typing text into textboxes). This enhancement request would like to see an option in the Configure Jenkins page under the Selenium section that would allow for the user to choose which version of IEDriverServer the plugin downloads to the node.

**Comment by Mobrockers** [comment]
As far as I know it is impossible for the 64bit driver version to drive a
32bit ie browser, as well as it is impossible for the 32bit driver to drive
a 64bit ie browser, this is not where the slowness comes from. It is
however true that the 64bit driver has a 5 second wait on every sendKeys
action and this is a documented flaw in the driver design so your request
certainly has merit. Keep in mind that due to a different flaw in the 32bit
driver it is impossible to take full screen screenshots when using the
32bit driver. These flaws should probably both be added as a warning on the
configuration page.

**Comment by zdmeyers** [comment]
I didnt know the 64-bit couldnt run the 32-bit browser and vice-versa. I always thought it opened whichever IE the driver told it to open. My mistake. But the option to choose which one is used would be nice. Some people care more about speed of test execution than being able to take full screenshots. And, even further on the screenshot topic, if Jenkins is running as a Windows service, you can't even see the browser being opened anayways due to Session 0 Isolation. This means that Selenium itself won't be able to take a screenshot at all. They just come out as all black.

**Comment by Mobrockers** [comment]
Is this for ie only? I have jenkins running as a Windows service myself and
it is possible to take screenshots at least for Chrome and ff.

**Comment by zdmeyers** [comment]
I have only ever tried running IE on Windows. I have some other OS's that we test FF on. But, we are moving to support Chrome as well now, so it is good to know that screenshots will work in Chrome. Everything I have read and experienced with Jenkins as a Windows service is just a major pain.

**Comment by Mobrockers** [comment]
For Chrome I recommend using the chromedriver plugin, it'll automatically
install the chromedriver for the right platform for every slave. I have
recently patched the download script to actually download the latest
version. It had been stuck in 2.9 for a while but is fully functional and
downloads version 2.21 now.

**Comment by Mobrockers** [comment]
While this is a good setting to have in the plugin as far as which version to **use**, I ultimately do not think this plugin should be download the iedriver at all see #64. Preferably a different plugin would handle the downloading etc, but this plugin should also have the option to specify which bitness to use. What do you think?

**Comment by zdmeyers** [comment]
If you are advising that the downloading of the IEDriverServer to slaves is broken into another plugin, then wouldn't the other plugin have the option to pick which one is downloaded? The Selenium plugin would then only have to know that the IEDriverServer is present (meaning, you might have to add in a config box where we can put in a path to the Executable or read from the configuration if the option exists for IE like it does for FF)

**Comment by Mobrockers** [comment]
I would think the other plug-in would download both because you might want
to use both in your tests, and in this plugin you would choose which one to
use for a given node, so that one can use different labels to request a
different bitness capability.

**Comment by zdmeyers** [comment]
Thats a better idea.
