### ISSUE TITLE
Plugin is creating large log files

### ISSUE THREAD

**Issue by harleyhooper1** [jenkinsci/selenium-plugin#81]
Selenium plugin is creating an extremely large log file which is consuming all available disk space, causing further issues with the build. 
The log file appears to be full of INFO logs, despite the log level being set to SEVERE

Selenium version is 2.53.0

Any help greatly appreciated as we are having to take the server offline every couple of days to remove the selenium.log file

**Comment by Mobrockers** [comment]
Plugin writes every request to logfile even with Log level set to SEVERE:

may 31, 2016 10:38:43 AM hudson.plugins.selenium.JenkinsCapabilityMatcher matches
INFO: CURRENT : {seleniumProtocol=WebDriver, jenkins.nodeName=(master), browserName=firefox, maxInstances=5, platform=WIN10}
may 31, 2016 10:38:43 AM hudson.plugins.selenium.JenkinsCapabilityMatcher matches
INFO: REQUEST : {browserName=chrome, version=, platform=ANY}

Note: You won't need to take the server nor jenkins offline to remove the logfile, simply restarting the selenium hub through the plugin will clear the logfile.

**Comment by pauliemcg** [comment]
We're having the same problem. The log file gets bigger and bigger and eventually the server runs out of space. This happens overnight so we are not able to restart the plugin until it's too late.

We've tried using the CLI safe-restart but there are other problems with that - that, of course is a separate issue.

If it was possible to get this resolved it would be very much appreciated.

Thanks

**Comment by Mobrockers** [comment]
I will take a look when I have time but I cannot promise when that will be,
sorry.

**Comment by pauliemcg** [comment]
OK - thanks very much for your quick response.

All of the work you do on this plugin (and others) is very much appreciated.

Thanks

**Comment by Mobrockers** [comment]
This issue will be fixed in the next release. I'll try to do a new release sometime in the following weeks, after I've fixed #79 as the new release **will** break the plugin for near everyone without that fix.

**Comment by pauliemcg** [comment]
That's great- thanks a lot

**Comment by Mobrockers** [comment]
The update has been released and should propagate to you soon!
