### ISSUE TITLE
Restarting Slave/Configuration causing IEDriverServer to be overwritten

### ISSUE THREAD

**Issue by zdmeyers** [jenkinsci/selenium-plugin#94]
If I already have a version of IEDriverServer on the slave machine, then restarting the node or configuration shouldn't overwrite the current one. I keep replacing the 64-bit IEDriverServer.exe with the 32-bit version, but when I restart the node or configuration, it gets replaced by the 64-bit version. I do not want to use the 64-bit version due to the slow typing issue.

**Comment by Mobrockers** [comment]
Duplicate of #72

**Comment by Mobrockers** [comment]
You can now choose your IEDriver version.
