### ISSUE TITLE
no where to change the default selenium options -host

### ISSUE THREAD

**Issue by michelleXIE2014** [jenkinsci/selenium-plugin#98]
I am using EC2 servers: a master jenkins and a slave. I created the selenium node in slave. Node successfully started but when I ran my tests I got

"UnknownServerException: Unable to connect to host 127.0.0.1 on port 7055"

My selenium options is "-port 5555 -maxSession 9 
-browser seleniumProtocol=WebDriver,browserName=firefox,maxInstances=9,version=45.3.0 
-host ip-172-17-0-1.ec2.internal "

the option "-host" always take this value " ip-172-17-0-1.ec2.internal ", which is not correct, where can I change this setting? I also checked the manage jenkins -> configure system -> selenium, no where to set the host. 

thank you

**Comment by zdmeyers** [comment]
Are you seeing the connection in the Selenium Grid page of Jenkins? Are you trying to run your tests from inside the EC2 network or outside the network? I know with AWS there is some settings you have to configure to allow connections into an instance from outside of AWS. The -host field is populated in this portion of the code inside SeleniumJarRunner.java:

`String nodehost = computer.getHostName();

        SeleniumRunOptions opts = initOptions(computer);

        if (opts != null) {
            opts.addOptionIfSet("-host", nodehost);
            computer.getNode().getRootPath()
                    .act(new SeleniumCallable(seleniumJar, htmlUnitDriverJar, nodehost, masterName, p.getPort(), nodeName, listener, name, opts));
        }`

The function getHostName() from the Computer object tries a bunch of different ways to compute the hostname of the node machine. It tries its best to figure out a hostname that is accessible to the master, pings that hostname from the master, and then uses it if the ping works.

According to code documentation that lead to a related JIRA ([HERE](https://issues.jenkins-ci.org/browse/JENKINS-5373)), you can setup a backup hostname by creating an environment variable called "host.name" and giving it the hostname you want. However, this will only work if the hostname is not able to be computed from the above function call to computer.getHostName().

**Comment by Mobrockers** [comment]
> I also checked the manage jenkins -> configure system -> selenium, no where to set the host.

This is not correct. manage jenkins -> configure system -> selenium; this has an option for setting a static hostname. Enable this option and you can set your own hostname.

**Comment by michelleXIE2014** [comment]
I set the hostname as well, but -host's value is not taking from hostname, correct?

**Comment by Mobrockers** [comment]
-host is the address of the hub the node should connect to. It *is* taken
from the hostname unless you explicitly change it by supplying your own
node options

**Comment by michelleXIE2014** [comment]
ew....Mine is not taken from the hostname I set in selenium option.I will check with our devops any way, thank you so much for your explanation @zdmeyers and @Mobrockers

**Comment by michelleXIE2014** [comment]
@zdmeyers the code is checked out to the slave as the selenium node, same server

**Comment by zdmeyers** [comment]
Did you restart both the Hub and Node after you changed the hostname in the Selenium settings? I know you have to restart both for the changes to propagate properly through the plugin. I personally use the option to make the Selenium plugin use the master hostname that is set through the Configure System menu and it works no problem

**Comment by Mobrockers** [comment]
No response, closing
